name             'ops-docker'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ops-docker'
long_description 'Installs/Configures ops-docker'
version          '0.1.0'
